(async () => {
  try {
  } catch (error) {
    console.log(`error at index.js : ${error}`);
  }
})();
